services:
  frontend:
    container_name: ${FRONTEND_CONTAINER_NAME}
    restart: always
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_DOCKER_PORT}:5000"
    depends_on:
      - api
    env_file:
      - .env
    networks:
      - newlife-network

  api:
    container_name: ${API_CONTAINER_NAME}
    restart: always
    build:
      context: ./api
    ports:
      - "${API_DOCKER_PORT}:5000"
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - newlife-network

  db:
    container_name: ${LOCAL_DB_CONTAINER_NAME}
    restart: always
    build:
      context: ./db
    environment:
      MYSQL_DATABASE: ${LOCAL_DB_NAME}
      MYSQL_USER: ${LOCAL_DB_USERNAME}
      MYSQL_PASSWORD: ${LOCAL_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${LOCAL_DB_PASSWORD}
      
    ports:
      - "${LOCAL_DB_PORT}:3306"
    env_file:
      - .env
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - newlife-network


networks:
  newlife-network:
    driver: bridge