openapi: 3.0.1
info:
  title: My API
  description: API for my application
  version: 1.0.0
servers:
  - url: http://localhost:5001
paths:
  /api:
    get:
      summary: Retrieve API information
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string