"""empty message

Revision ID: 49ceff5b71c2
Revises: 
Create Date: 2025-01-19 22:11:35.136320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49ceff5b71c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('health_nutrition')
    op.drop_table('health_nutrition_menu')
    op.drop_table('hobbies_activity_log')
    op.drop_table('health_weight')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_weight',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('weight', mysql.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('imc', mysql.FLOAT(), nullable=False),
    sa.Column('body_fat', mysql.FLOAT(), nullable=False),
    sa.Column('subcutaneous_fat', mysql.FLOAT(), nullable=False),
    sa.Column('visceral_fat', mysql.FLOAT(), nullable=False),
    sa.Column('muscle_mass', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('hobbies_activity_log',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('rating', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category', mysql.VARCHAR(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('health_nutrition_menu',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('day_of_week', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('menu_week_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('breakfast_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('breakfast_snack_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('lunch_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('afternoon_snack_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('dinner_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('night_snack_id', mysql.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['afternoon_snack_id'], ['health_nutrition.id'], name='health_nutrition_menu_ibfk_4'),
    sa.ForeignKeyConstraint(['breakfast_id'], ['health_nutrition.id'], name='health_nutrition_menu_ibfk_1'),
    sa.ForeignKeyConstraint(['breakfast_snack_id'], ['health_nutrition.id'], name='health_nutrition_menu_ibfk_2'),
    sa.ForeignKeyConstraint(['dinner_id'], ['health_nutrition.id'], name='health_nutrition_menu_ibfk_5'),
    sa.ForeignKeyConstraint(['lunch_id'], ['health_nutrition.id'], name='health_nutrition_menu_ibfk_3'),
    sa.ForeignKeyConstraint(['night_snack_id'], ['health_nutrition.id'], name='health_nutrition_menu_ibfk_6'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('health_nutrition',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('food_type', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('portion', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('example', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('recipe', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
