"""Vacio

Revision ID: aad50449f186
Revises: 
Create Date: 2025-01-25 21:36:30.818165

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aad50449f186'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goals_objective')
    op.drop_table('goals_goal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals_goal',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('goals_objective',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('start_number', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('end_number', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_boolean', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('start_value', mysql.FLOAT(), nullable=True),
    sa.Column('end_value', mysql.FLOAT(), nullable=True),
    sa.Column('currency_unit', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('goal_id', mysql.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals_goal.id'], name='goals_objective_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
